{{- if .Values.query.tlsClient.enabled }}
apiVersion: v1
data:
  client.crt: {{ .Values.query.tlsClient.cert | b64enc }}
  client.key: {{ .Values.query.tlsClient.key | b64enc }}
  ca.crt: {{ .Values.query.tlsClient.ca | b64enc }}
kind: Secret
metadata:
  name: {{ include "thanos.fullname" . }}-thanos-query-tls-client
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: query
type: Opaque
{{- end -}}
