{{- if .Values.query.tlsServer.enabled }}
apiVersion: v1
data:
  tls.crt: {{ .Values.query.tlsServer.cert }}
  tls.key: {{ .Values.query.tlsServer.key }}
  ca.crt: {{ .Values.query.tlsServer.ca }}
kind: Secret
metadata:
  name: {{ include "thanos.fullname" . }}-thanos-query-tls-server
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: query
type: Opaque
{{- end -}}
