{{- if .Values.query.tlsClient.enabled }}
{{- if not .Values.query.tlsClient.secretName }}
apiVersion: v1
data:
  tls.crt: {{ .Values.query.tlsClient.cert }}
  tls.key: {{ .Values.query.tlsClient.key }}
  ca.crt: {{ .Values.query.tlsClient.ca }}
kind: Secret
metadata:
  name: {{ include "thanos.fullname" . }}-thanos-query-tls-client
  labels:
    app.kubernetes.io/name: {{ include "thanos.name" . }}
    helm.sh/chart: {{ include "thanos.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: query
type: Opaque
{{- end -}}
{{ end }}

