image:
  repository: improbable/thanos
  tag: v0.3.2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

# TODO: this should be removed in favor of objectStorageConfig, keeping it now for backward compatibility
s3:
  enabled: false
  bucket: ""
  endpoint: ""
  insecure: false
  signatureV2: true
  encryptSse: false

# Thanos object storage configuration (Azure Blob, EWS S3, etc.)
# see ref: https://github.com/improbable-eng/thanos/blob/master/docs/storage.md
objectStorageConfig:
  enabled: false
  key: thanos.yaml
  name: thanos-objstore-config

# Thanos store configuration
store:
  enabled: true
  replicaCount: 1
  logLevel: debug
  clusterDisabled: true

  # cert, key and ca are strings and can be overwritten using `helm install <chart> --set-file <key>=/path/to/file`
  tlsServer:
    enabled: false
    # certificate and key for server TLS
    cert: ""
    key: ""
    # CA to validate the remote client certificate
    ca: ""

  deployment:
    annotations: {}
      # iam.amazonaws.com/role: prometheus-thanos-store

    container:
      httpPort: 10902
      grpcPort: 10901
      clusterPort: 10900

  clusterDisabled: true

  clusterService:
    enabled: false
    type: ClusterIP
    port: 10900
    nodePortEnabled: false
    nodePort: 30900
    externalTrafficPolicy: ""
    annotations: {}

  grpcService:
    enabled: true
    type: ClusterIP
    port: 10901
    nodePortEnabled: false
    NodePort: 30901
    externalTrafficPolicy: ""
    annotations: {}

  httpService:
    enabled: true
    type: ClusterIP
    port: 10902
    nodePortEnabled: false
    nodePortEnabled: false
    nodePort: 30902
    externalTrafficPolicy: ""
    annotations: {}

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

# Thanos query configuration
query:
  enabled: true
  replicaCount: 1
  logLevel: debug
  stores:
    - store.example.local:10901
  queryReplicaLabel: replica

  # cert, key and ca are strings and can be overwritten using `helm install <chart> --set-file <key>=/path/to/file`
  tlsClient:
    enabled: false
    # certificate and key for client side authentication to stores
    cert: ""
    key: ""
    # CA to validate the remote store certificate
    ca: ""
    # (optional) server name indication to the stores (ref: https://tools.ietf.org/html/rfc4366#section-3.1)
    serverName: ""

  # cert, key and ca are strings and can be overwritten using `helm install <chart> --set-file <key>=/path/to/file`
  tlsServer:
    enabled: false
    # certificate and key for server TLS
    cert: ""
    key: ""
    # CA to validate the remote client certificate
    ca: ""

  deployment:
    annotations: {}
      # iam.amazonaws.com/role: prometheus

    container:
      httpPort: 10902
      grpcPort: 10901
      clusterPort: 10900

  clusterDisabled: true

  clusterService:
    enabled: false
    type: ClusterIP
    port: 10900
    nodePortEnabled: false
    nodePort: 30900
    externalTrafficPolicy: ""
    annotations: {}

  grpcService:
    enabled: true
    type: ClusterIP
    port: 10901
    nodePortEnabled: false
    NodePort: 30901
    externalTrafficPolicy: ""
    annotations: {}

  httpService:
    enabled: true
    type: ClusterIP
    port: 10902
    nodePortEnabled: false
    nodePortEnabled: false
    nodePort: 30902
    externalTrafficPolicy: ""
    annotations: {}

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #  cpu: 100m
    #  memory: 128Mi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

# Thanos compact configuration
compact:
  enabled: false
  replicaCount: 1

  syncDelay: 30m
  retentionResolutionRaw: 0d
  retentionResolution5m: 0d
  retentionResolution1h: 0d
  wait: true

  logLevel: debug

  clusterDisabled: true

  deployment:
    annotations: {}
      # iam.amazonaws.com/role: prometheus-thanos-store

    container:
      httpPort: 10902
      grpcPort: 10901
      clusterPort: 10900

  httpService:
    enabled: true
    type: ClusterIP
    port: 10902
    nodePortEnabled: false
    nodePortEnabled: false
    nodePort: 30902
    externalTrafficPolicy: ""
    annotations: {}
